### ISSUE TITLE
[JPA] 

### ISSUE THREAD

**Issue by hskim1226** [HomoEfficio/demo-mall#11]
### 1번 JPQL코드
```java
@Repository
public interface ProjectRepository extends JpaRepository<Project,Integer> {
 @Query("select a.project, count(a.memberCode) as memberNum " +
            "from Member1 a " +
            "where a.project.projectFlag = :projectFlag " +
            "group by a.project")
    Page<Project> findProjectAndMember(@Param("projectFlag") String projectFlag, Pageable pageable);

```
### 2번 실행결과
![image](https://user-images.githubusercontent.com/24791648/27906247-bdc147ac-627d-11e7-9aab-3c305aa99c8f.png)

### 3번 Native Query
```java
@Query(value = "select user_id, user_name from users ", nativeQuery = true)
List<Object[]> findUSBCandidates();
```
```
◾ Native Query는 Repository에서 @Query(value=“쿼리문”, nativeQuery = true)로 수행한다.
◾ 컬럼이 하나 혹은 엔티티 객체일 경우에는 리턴값을 해당 타입 혹은 해당 타입의 리스트로 지정한다.
◾ 다중 컬럼일 경우에는 Object []로 받아서 컬럼 지정 순서대로 값을 뽑아서 사용한다.
```

프로젝트의 맴버 수를 구해서 `memberNum`에 넣고 싶어서  , `1번` 방식으로 jpql을 적용하였습니다.
그런데 `2번`의 결과를 보니 ,  Project객체로 넘겨주었음에도 불구하고 ,  배열로 전달이 된것을 확인 하였습니다. 그래서 찾아보니 `3번` `다중 컬럼일 경우에는 Object []로 받아서 컬럼 지정 순서대로 값을 뽑아서 사용한다.` 라고 합니다.

**Comment by HomoEfficio** [comment]
두 가지 방법이 떠오르는데요, 

1. JPA 책의 363페이지에 있는 것처럼, `select new Project(..., count(a.memberCode), ... ) from Project a ...`를 이용하는 방법

1. Repository에서는 위 1번 처럼 받아오고, Service 레이어에서 `returnProject.memberNum = object[1]` 대략 이런 식으로 새로운 Project를 만들어서 Controller에 반환해주는 방법

제 생각에는 1번 방식이 나은 것 같습니다.

이것도 해 보시고 결과 알려주시면 좋겠습니다. ^^

**Comment by haeyon098** [comment]
답변을 확인하기 전에 검색해서 1번 방법을 찾아서 수행했습니다. 
원하는 대로 `Project`의 `memberNum` 변수 안에 `count(a.memberCode)`값이 들어간 것을 확인할 수 있었어요. 감사합니다~
