### ISSUE TITLE
Domain/DTO/VO & Repository 구분 및 정의

### ISSUE THREAD

**Issue by haeyon098** [HomoEfficio/demo-mall#3]
## Domain 
- 테이블과 1:1 매핑됨
- 테이블을 표현한 객체
## DTO
- 파라미터 객체
## VO
- Value Object의 약자로, Value만 담고 있는 객체
## Repository
- CRUD 기능을 가지고 있고, CRUD 결과를 반환해줌

**쇼핑몰 예제를 보며, 사용된 개념들을 위와 같이 이해했습니다.** 
## 궁금증
**Q1. 각각의 개념과 역할을 위와 같이 이해하고 예제를 접근하는게 맞나요? 그렇지 않다면, 어떤 역할로 사용하셨나요?
Q2. DTO와 Domain의 차이가 미묘하게 느껴집니다. DTO 없이 Domain만 사용한다면 어떤 문제점/불편함이 발생할 수 있나요?**

**Comment by HomoEfficio** [comment]
A1. 
일단 거의 제대로 이해하신 것 같습니다.
한 가지만 부연 설명하자면, 항상 RDBMS를 사용하는 것은 아니므로 도메인 객체가 꼭 RDBMS 테이블과 1:1 매칭이 된다라고 이해하기 보다는, 식별자가 필요한 어떤 저장구조(RDMS라면 테이블이 맞겠죠)와 1:1 매칭이 된다는 게 조금 더 나을 것 같습니다.

A2.
DTO는 뷰 단에까지 사용됩니다. 따라서 DTO 없이 Domain만 사용한다면 Domain 객체가 뷰 단에까지 사용되어야 하며, 결국 뷰 단의 로직이 포함됩니다. 
이를 용인한다면 DTO 없이 Domain 객체만으로 뷰-컨트롤러-서비스-리파지토리 등의 모든 레이어를 감당해야하고, Domain 객체에 비즈니스 로직과 뷰 로직이 혼재되는 상황이 발생합니다.
그게 별 문제가 아니라는 접근 방식이면 DTO를 굳이 사용하지 않아도 됩니다.
하지만 Domain 객체에는 가능한 비즈니스 로직만 담고 싶다면 뷰 로직을 담당하는 DTO를 함께 사용하는 것이 나은 선택이 되겠죠.
