### ISSUE TITLE
객체 사용 질문 입니다.

### ISSUE THREAD

**Issue by hskim1226** [HomoEfficio/demo-mall#4]
#### controller
```
    @GetMapping("/main/{userName}")
    public ModelAndView signIn(@PathVariable("userName") String userName, HttpSession session, ModelAndView mv) {
        mv.setViewName("main");
        session.setAttribute("userName", userName);
        setUserInfo(userName, mv);
        return mv;  // main 화면에서 memberId로 장바구니 조회해서 있으면 표시하도록
    }
```

### main.ftl
```
<form id="myForm2" v-on:submit.prevent="sendPost()">
userNmae : {{ userName}}
    <input type="text" name="userName" v-model="userName"><br>
    <textarea name="birthYear" v-model="birthYear"></textarea><br>
    <input type="submit" value="Search" class="btn">
</form>

<script>
    new Vue({
        el: '#myForm2',
        data: {
            userName: '${Session.userName}',
            birthYear: '1990'
        }  ,
        methods: {
                sendPost() {
                    axios.post('/posttest/', {
                        userName: this.userName,
                        birthYear: this.birthYear
                    }).then(res => {
                                console.log(res);
                            })
                            .catch(err => {
                                console.log(err);
                            });
                },
            }
        });
</script>
```
* 프리마커 문법인 ${} 내장객체를 사용하여 프리마커 파일안에 아래와 같이 작성해보았습니다.
* userName 같은 경우 , 초기 값을 controller로 부터 가져온 값으로 설정 하고 싶어서 이렇게 작성 해 보았습니다.
* 실제 사용된 예제 에서는   ` userName: 'hs' ` 같은 형대로 , staic하게 고정 되어있었는데요
* 프리마커 안에 script를 함께 사용 하면  위와 같이 사용 할수 있는데

**Comment by HomoEfficio** [comment]
1. js로 따로 분리한다면 controller에서 js에 값을 넣어줄 방법이 없어지죠. 따라서, js에서 axios등을 이용해서 서버에 요청을 보내서 원하는 값을 다시 받아와야 합니다. 이런 방식도 예제 코드가 있으니 참고해보세요.

2. 뭐.. 일단 동작한다면 '잘못된' 방식이라고 하기 보다는 목적에 적합하냐 안 하냐로 구분하는게 나을 것 같고요, ^^
전에 말씀드린대로 서버에서는 html 없이 json 등 필요한 데이터만 반환하고 화면에 그리는 일은 화면에서 담당하는 방식으로 정했다면, 위 방식보다는 js내의 vue.js 코드의 create() {} 또는 mounted() {} 내에서 서버에 요청을 보내고 필요한 값을 받아와서 화면을 그리는게 적합할테고요,
그냥 컨트롤러가 html을 포함한 뷰 코드 전체를 반환하는 방식으로 한다면, 위와 같이 해도 됩니다.

**Comment by hskim1226** [comment]
### 생명 주기(Lifecycle)
Vue.js에서 뷰 모델이 생성되는 순간부터 중요한 사이클이 시작된다

beforeCreate ~ created : 데이터 및 이벤트 초기화
created ~ beforeMount : 뷰 생성
mounted ~ updated : 데이터 바인딩, 데이터 변경 주시 및 뷰 업데이트
destroyed : 자식 컴포넌트, 이벤트 리스너 해제
![image](https://user-images.githubusercontent.com/24791648/27412891-fa32f498-5732-11e7-8df0-04bd3576f5f8.png)
