### ISSUE TITLE
[JPA] update 질문입니다

### ISSUE THREAD

**Issue by hskim1226** [HomoEfficio/demo-mall#6]
#### SQL문
```
		UPDATE
		project SET
		projectFlag='0',userId=#{userId}
		WHERE
		projectCode=#{projectCode}
````
일때 ,  update하고 싶은 값만 변경 할수 있는데요

#### JPA
```
 public void delete(int projectCode) {
        Project project = projectRepository.findOne(projectCode);

        project.setProjectFlag("0");
       project.getUser().setUserId("gcssystem");  

        projectRepository.save(project);
    }
```
find를 통해서  project객체를 받은 다음에 , 거기서 update하고 싶은 값을 변경해서 save 하는 방법을 사용해야 하는것 인가요?
#### 2번의 과정을 거져야 하는 것인가요?  위의 방법 말고 다른 방법도 있나요?

**Comment by HomoEfficio** [comment]
이미 한 번 findOne으로 가져온 객체에는 set만 하면 되고, 맨 마지막의 save를 따로 안 해주셔도 될 겁니다. 꼭 테스트 해보시고 확실히 확인해보세요.
