### ISSUE TITLE
[JPA] 트랜잭션 범위의 영속성 컨텍스트 질문 입니다.

### ISSUE THREAD

**Issue by hskim1226** [HomoEfficio/demo-mall#7]
#6 의 연장 질문 입니다
```
@Transactional
public class ProjectService {
public void delete(int projectCode) {
     
        Project project = projectRepository.findOne(projectCode);
        project.setProjectFlag("0");
        
    }
}
```
### update를 다시 하지 않아도 되는 이유가 
```
1. @Transactional  선언해서 트랜잭션 시작 
2. project는 영속 상태 
    projectRepository.findOne(projectCode) 통해 조회한 project엔티티는
   트랜잭션 범위 안에 있으므로 ,영속성 컨텍스트의 관리를 받는다
3. project는 영속 상태로 변경 감지가 가능한다
4. @Transactional 선언한 메소드가 정상 종료 되면 
   1. 트랜잭션 커밋 = 영속성 컨텍스트 종료 = 엔티티 매니저 플러시가 호출
   2. 스냅샷으로 변경된 엔티티 찾는다
   3. 변경된 엔티티가 있으면  수정 쿼리를 생성해서 , 쓰기 지연 sql 저장소에 보낸다
   4. 쓰기 지연 저장소의 sql을 데이터 베이스에 보낸다
   5. 데이터베이스의 트랜잭션을 커밋한다
```
 위의 내용으로 이해가 됩니다.
찾아보니  트랜잭션 범위와 영속성 컨텍스트의 생존 범위가 같고 
###  같은 트랜잭션 안에서는 항상 같은 영속성 컨텍스트에 접근한다
라고 하는데 

### 각각의 메소드가 각각의 트랜잭션을 시작하고 , 각각의 메소드에서 컨텍스트 생존범위가 존재하는 걸로 이야하면 될까요 ?
(=메소드 마다 다른 트랜잭션이 생기고 , 영속성 컨텍스트가 메소드 마다 다르게 생기는 것이 맞나요?)

**Comment by HomoEfficio** [comment]
열심히 공부하셨군요! ^^

1. 클래스 단에 `@Transactional`을 적용하면 메서드마다 트랜잭션이 생기는가? 

    맞습니다. 자세한 내용은 `토비의 스프링 책 > 트랜잭션 애노테이션 > 대체 정책`을 읽어보시면 정확히 알게 될 겁니다.

2. 영속성 컨텍스트가 메서드마다 다르게 생기는것이 맞는가?

    맞습니다. 다만 더 정확히 말하면 영속성 컨텍스트는 트랜잭션 마다 생기고, 보통 서비스 메서드 하나가 트랜잭션 단위인 경우가 많으므로 결과적으로 영속성 컨텍스트가 메서드마다 생긴다라는 말이 틀리지 않게 되는 겁니다.

     관련 내용은 JPA 책 13장 앞부분에 잘 나와 있습니다.

화이팅! ^^
