### ISSUE TITLE
#8 연장 질문 입니다

### ISSUE THREAD

**Issue by hskim1226** [HomoEfficio/demo-mall#9]
#8  말씀하신 props는 
```
1 ) main.js 
     addCart 메소드 호출  -> this.addedItem = this.items[index];
2)  component-cart.js 
    addedItem(main.js선언) 변화 감지  ->   this.addToCart(addedItem);
    watch: {
        addedItem(addedItem) {
            this.addToCart(addedItem);
        }
    }
```
이렇게 이해가 됩니다.

# 제가 지금 하려는 부분은 ,component.js에서 받은 값을  프로젝트.js로 넘기려고 합니다.이것도 props로 사용하면 된다는 말씀인가요.?
(컴포넌트에서 넣은 데이터객체인 `result`를  프로젝트리스트.js의 `projectResults`에 어떻게 데이터를 전달해야 할지 모르겠습니다.)

 이렇게 컴포넌트를 구현하려는 이유는  
아래의 `3가지 결과화면` 에서 , 가져오는 데이터 값은 같고 , 화면에서 버튼 종류가 다르기 때문에
 `검색` 이라는 컴포넌트를 따로 빼서, 검색 컴포넌트를 통해서 초기 값 세팅과 , 검색 결과값 세팅을 공통으로 해주고
버튼을 설정하는 다른 버튼 부분은 프리마커로 하려 합니다.

## 결과 화면 
![image](https://user-images.githubusercontent.com/24791648/27816520-030246f8-60c7-11e7-90b9-fb8955dbe683.png)
------
![image](https://user-images.githubusercontent.com/24791648/27816524-0a3bc390-60c7-11e7-8a75-7c686f15bac6.png)
------
![image](https://user-images.githubusercontent.com/24791648/27816528-1186ccd0-60c7-11e7-8102-a878dfc3581f.png)

### `검색` 컴포넌트
` >>> 검색 탬플릿`
![image](https://user-images.githubusercontent.com/24791648/27816606-8f1cadae-60c7-11e7-8f46-c14eee31d549.png)

```
Vue.component('project-search', {
    template: `
           >>> 검색 탬플릿
    `,
    data() {
        return {
         results: {}
        };
    },
    methods: {
        onSearch() {
          >>> this.results  = 검색 결과 데이터 가져오기
        }
    },
    created() {
      >>>  this.results = 초기 전체 데이터 가져오기 
});

`````

### 프로젝트리스트 .js
```
new Vue({
    el: '#app',
    data: {
        projectResults: {},
    }
```
### 프로젝트리스트 .프리마커

```
<h1 class="link">프로젝트 리스트</h1>
 <project-search  ></project-search>

   <div class="product" v-for="(item, index) in projectResults">
 <p>작업 위치: {{ item.project.projectPlaceAddress }}</p>
   <div v-if="item.authorityCode == '02'">
   <button class="btn add-to-cart" @click="modifyProject(item.project.projectCode)">수정</button>                    
    </div>
```

# 이런경우 컴포넌트로 빼는것이 아닌 것인가요 .?
# 이런 경우에도 props를 이용하는 것이 맞나요?

**Comment by hskim1226** [comment]
#8 에서 실행이 되었다고 말씀드린 부분이 $parent를 이용해서 였는데요
찾아보니
```
this.$parent 피하기
Vue.js는 부모 컨텍스트에 접근 할 수 있는 중첩 컴포넌트를 지원합니다. 하지만 Vue 컴포넌트 외부의 컨텍스트에 접근하면 컴포넌트 기반 개발의 FIRST 규칙을 위반하게 됩니다. 따라서 this.$parent를 사용을 피해야합니다.

왜 그렇게 하나요?
Vue 컴포넌트는 다른 모든 컴포넌트와 마찬가지로 독립적으로 작동해야합니다. 컴포넌트가 부모에 접근해야할 경우 이 규칙은 무너지게 됩니다.
컴포넌트가 부모에 접근하는 경우 다른 곳에서 재사용할 수 없습니다.
어떻게 하나요?
어트리뷰트/프로퍼티를 사용하여 부모에서 자식 컴포넌트로 값을 전달합니다.
어트리뷰트 표현식에서 콜백을 사용하여 부모 컴포넌트에 정의된 메소드를 자식 컴포넌트로 전달하십시오.
자식 컴포넌트에서 이벤트를 emit하여 부모 컴포넌트에서 이벤트를 발생시킵니다.
```
라고 하여서 , 아래와 같이 코드를 수정했습니다.

### 프리마커
```
<project-search @change="projectEvent($event)"></project-search>
```

### 프로젝트.js

```

new Vue({
    el: '#app',
    data: {
        projectResults: {},
    },
    methods: {
        projectEvent($event) {
             this.projectResults= $event
        },
```

### 컴포넌트.js

```
methods: {
        onSearch() {
               axios.get(this.memberView+'/search/'.concat(this.searchType).concat('/').concat(this.newSearch))
                    .then(res => {
                        this.$emit('change', this.results);      
                    })
        }
    },
```
### 말씀하신거는 props를 이용해서 였는데 , 그렇게 하는쪽으로는 방법을 잘 모르겠어서 이렇게 수정해봤는데 , 이방법도 괜찮나요?

**Comment by HomoEfficio** [comment]
수고 많으시네요!

위 방법은 괜찮아 보입니다. 괜찮냐 마냐의 기준은 저도 답변드렸고, 위에 검색해서 찾아보신 결과에도 나온 것처럼, **컴포넌트의 재사용성이 유지되느냐 마느냐** 입니다.

>컴포넌트의 재사용성이 유지된다면 일단 합격입니다.

제가 말씀드린 `props`를 활용하는 방법으로 하려면,

Freemarker에서는 `<project-search  ></project-search>`로 컴포넌트를 불러들일 것이 아니라, `<project-search  :projectResults='projectResults'></project-search>`처럼 컴포넌트에 `projectResults`를 전달하면서 컴포넌트를 불러들이고, 

컴포넌트 내에서는 `props`로 `projectResults`를 받아서, `this.projectResults = this.results`로 `projectResults`에 값을 넣자. 입니다.

그런데 혹시 `props`로 넘어가는 변수는 읽기만 가능하고, 쓰기는 불가능하다면 `props` 방식으로는 해결이 불가능하고 찾아보신 방식으로 해야합니다.

`props`로도 한 번 해보시고 되는지 결과 알려주세요.

**Comment by hskim1226** [comment]
실행 결과  
```
Avoid mutating a prop directly since the value will be overwritten 
whenever the parent component re-renders.
 Instead, use a data or computed property based on the prop's value. 
Prop being mutated: "projectResults"

```
에러 로그가 뜹니다 !
감사합니다~

**Comment by HomoEfficio** [comment]
역시 쓰기는 불가군요! 덕분에 저도 하나 배웁니다! 고맙습니다~
